#!/usr/bin/env sh
# =============================================================================
# UniVim svim.sh - DO NOT EDIT THIS FILE DIRECTLY
# =============================================================================
# This file may be overwritten on UniVim updates. To customize, create your
# own script and source this file from it, or copy this file to a backup
# location and modify the copy.
#
# This script is executed when:
#   - The vim mode changes ($MODE: N/I/V/C)
#   - The commandline changes ($CMDLINE)
#   - The VN input mode toggles ($VNMODE: on/off)
#   - A config error occurs ($UNIVIM_CONFIG_ERROR)
# =============================================================================

# Show macOS notification for config errors
if [ -n "$UNIVIM_CONFIG_ERROR" ]; then
    osascript -e "display notification \"$UNIVIM_CONFIG_ERROR\" with title \"UniVim Config Error\"" 2>/dev/null
    exit 0
fi

# =============================================================================
# Example: SketchyBar integration (uncomment to use)
# =============================================================================
# The variables $MODE and $CMDLINE hold the current editor and cmdline info

# COLOR=0xff9dd274
# if [ "$MODE" = "" ]; then
#   COLOR=0xffff6578
# fi
#
# DRAW_CMD="off"
# if [ "$CMDLINE" != "" ]; then
#   DRAW_CMD="on"
# fi
#
# sketchybar --set svim.mode label="[$MODE]" \
#                            label.drawing=$(if [ "$MODE" = "" ]; then echo "off"; else echo "on"; fi) \
#                            icon.color=$COLOR \
#                            popup.drawing=$DRAW_CMD \
#            --set svim.cmdline label="$CMDLINE"
#
# This is the setup command needed for sketchybar in sketchybarrc:
#
# sketchybar --add item svim.mode right \
#            --set svim.mode popup.align=right \
#                            icon= \
#                            icon.font="Hack Nerd Font Mono:Bold:28.0" \
#                            label.font="Hack Nerd Font Mono:Bold:13.0" \
#                            icon.color=0xffff6578 \
#                            script="sketchybar --set svim.mode popup.drawing=off" \
#            --subscribe svim.mode front_app_switched window_focus \
#            --add item svim.cmdline popup.svim.mode \
#            --set svim.cmdline icon="Command: "
#
